export const routes = {
  LANDING: "/",
  LOGIN: "/login",
  USER_SIGNUP: "/user/signup",
  BOOKING_UPLOAD: "/user/booking/upload",
  BOOKING_PREFERENCES: "/user/booking/preferences", 
  BOOKING_SCHEDULING: "/user/booking/scheduling",
  BOOKING_MATCHES: "/user/booking/matches",
  BOOKING_CONFIRM: "/user/booking/confirm",
  BOOKING_SUCCESS: "/user/booking/success",
  USER_DASHBOARD: "/user/dashboard",
  USER_MESSAGES: "/user/messages",
  USER_EXPLORE: "/user/explore",
  USER_BOOKINGS: "/user/bookings",
  USER_PROFILE: "/user/profile",
};